# -*- coding: utf-8 -*-
"""demo_infer_imgcap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nw7hxhLm1C9adHFVWr752AS5z-Y-uDPR

#Custom image infer
"""

#!!python /content/drive/MyDrive/image_caption/custom_img_infer.py [PATH TO IMAGE DATA FOLDER]

!python /content/drive/MyDrive/image_caption/custom_img_infer.py '/content/test_folder'

"""#Infer with Flicker8k Dataset"""

#!!python /content/drive/MyDrive/image_caption/infer.py [PATH TO FLICKER TEXT FOLDER] [PATH TO FLICKER DATASET FOLDER]

!python /content/drive/MyDrive/image_caption/infer.py '/content/flicker_text' '/content/Flicker8k_Dataset'

