# -*- coding: utf-8 -*-
"""demo_imgcap.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nw7hxhLm1C9adHFVWr752AS5z-Y-uDPR
"""

!unzip '/content/drive/MyDrive/Flickr8k_Dataset.zip'

import os
os.mkdir('flicker_text')

from zipfile import ZipFile
with ZipFile('/content/drive/MyDrive/Flickr8k_text.zip', 'r') as zipObj:
   # Extract all the contents of zip file in current directory
   zipObj.extractall('/content/flicker_text')

import sys
sys.path.insert(0,'/content/drive/MyDrive/image_caption')

os.makedirs("model_res", exist_ok=True)

#!python path_to_training_script [PATH TO TEXT FILE] [PATH TO DATASET FOLDER] [NUMBER OF EPOCHS]
!python /content/drive/MyDrive/image_caption/train.py '/content/flicker_text' '/content/Flicker8k_Dataset' 1

